using EpamString;

CustomString a = new CustomString("abcdef");
Console.WriteLine(a);
Console.WriteLine(a.Count);
Console.WriteLine(a.Capacity);
Console.WriteLine(a[3]);
a.Append('s');
Console.WriteLine(a);
Console.WriteLine(a.Count);
Console.WriteLine(a.Capacity);
Console.WriteLine(a[3]);
a.Append("new");
Console.WriteLine(a);
Console.WriteLine(a.Count);
Console.WriteLine(a.Capacity);
a.Append("new");
Console.WriteLine(a);
Console.WriteLine(a.Count);
Console.WriteLine(a.Capacity);
a.Insert('S', 4);
Console.WriteLine(a);
Console.WriteLine(a.Count);
Console.WriteLine(a.Capacity);
a.Insert("SASD", 4);
Console.WriteLine(a);
Console.WriteLine(a.Count);
Console.WriteLine(a.Capacity);
a.Remove(4, 5);
Console.WriteLine(a);
Console.WriteLine(a.Count);
Console.WriteLine(a.Capacity);
Console.WriteLine(a.FindFirstString("hah"));
Console.WriteLine(a.FindFirstString("de"));
Console.WriteLine(a.FindFirstChar('z'));
Console.WriteLine(a.FindFirstChar('e'));
a.Replace("de", "KY");
Console.WriteLine(a);
Console.WriteLine(a.Count);
Console.WriteLine(a.Capacity);
a.Replace("f", "KYKYKYKYKYKYKYKYKY");
Console.WriteLine(a);
Console.WriteLine(a.Count);
Console.WriteLine(a.Capacity);
CustomString b = new CustomString(a.ToString());
Console.WriteLine(b);
Console.WriteLine(b.Count);
Console.WriteLine(b.Capacity);
Console.WriteLine(a.Equal(b));
b.Replace("KY", "z");
Console.WriteLine(b);
Console.WriteLine(b.Count);
Console.WriteLine(b.Capacity);
Console.WriteLine(a.Equal(b));